version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/DBC"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
- package-ecosystem: nuget
  directory: "/src/DBC.Tests"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
