version: 2
updates:
- package-ecosystem: nuget
  directory: /samples/dotnet/
  schedule:
    interval: daily
- package-ecosystem: maven
  directory: /samples/java/
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: /samples/javascript/
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: /samples/ruby/
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: /src/DCB.Tests/
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: /src/DCB/
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
