version: 2
updates:
- package-ecosystem: nuget
  directory: \samples\dotnet\Dotnet.csproj
  schedule:
    interval: daily
- package-ecosystem: maven
  directory: \pom.xml
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: \src\DCB.Tests\DCB.Tests.csproj
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: \src\DCB\DCB.csproj
  schedule:
    interval: daily
